[features]
seeds = false
[programs.localnet]
crowdfunding = "C8eV1vTKvvgwyk7TKGDrXouRCs9bfLx1c6EKGrkj1pck"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://explorer-api.devnet.solana.com/"
wallet = "/Users/zazza/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
